version: "3.7"

services:
  server:
    image: nginx:alpine
    working_dir: /application
    restart: unless-stopped
    tty: true
    volumes:
      - .:/application
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8334:80"

  gui:
    image: node:13.8.0
    working_dir: /application
    command: npm run build
    volumes:
      - .:/application

  api:
    image: composer:1.9.1
    working_dir: /application
    command: composer build
    volumes:
      - .:/application