version: "3.7"

services:
  web:
    image: nginx:1.19-alpine
    container_name: browary-web
    working_dir: /application
    restart: unless-stopped
    tty: true
    volumes:
      - .:/application
      - ./environment/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "${EXTERNAL_WEBSERVER_PORT}:80"

  php:
    image: ghcr.io/blumilksoftware/php:8.0.5.0
    container_name: browary-php
    working_dir: /application
    user: ${CURRENT_UID}
    volumes:
      - .:/application

  node:
    image: node:15.5.1-alpine3.10
    container_name: browary-node
    working_dir: /application
    user: ${CURRENT_UID}
    volumes:
      - .:/application
    tty: true
    environment:
      - HOST=0.0.0.0
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "${DEVELOPMENT_NODE_PORT}:${DEVELOPMENT_NODE_PORT}"
