version: "3.7"

services:
  server:
    image: nginx:alpine
    working_dir: /application
    restart: unless-stopped
    tty: true
    volumes:
      - .:/application
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8334:80"

  api:
    image: composer:2.0
    working_dir: /application
    command: composer build
    volumes:
      - .:/application

  gui:
    image: node:13.8.0
    working_dir: /application
    command: npm run build
    volumes:
      - .:/application

  gui-dev:
    image: node:13.8.0
    working_dir: /application
    command: npm run serve
    volumes:
      - .:/application:cached
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
    tty: true
    environment:
      - HOST=0.0.0.0
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "8335:8335"