name: Build and deploy

on:
  pull_request:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Install PHP dependencies
        run: |
          composer install

      - name: Run code style checker
        run: |
          composer ecs
