name: Build and deploy

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 8 1 * *"

jobs:
  deploy:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install and build frontend
        env:
          VITE_MAPBOX_TOKEN: "${{ secrets.VITE_MAPBOX_TOKEN }}"
          VITE_MAPBOX_STYLE_URL: "${{ secrets.VITE_MAPBOX_STYLE_URL }}"
        run: |
          npm install
          npm run-script build

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          coverage: none

      - name: Install and build backend
        run: |
          composer install
          echo 'VITE_MAPBOX_TOKEN="${{ secrets.VITE_MAPBOX_TOKEN }}"' > .env
          composer build

      - name: Handle 404 for GitHub Pages
        run: cp index.html 404.html
        working-directory: public

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          BRANCH: public
          FOLDER: public
          CLEAN: true
